### ISSUE TITLE
Missing element in doc

### ISSUE THREAD

**Issue by LaMonF** [bacardi55/kalliope-repeat#1]
Hey,

Just checking your repo, thanks for the couple of neurons you made \o/.

Find out you forget to add the [Options](https://github.com/bacardi55/kalliope-repeat#options)
Same with the [Return values](https://github.com/bacardi55/kalliope-repeat#return-values)

Also you need to [indent correctly](https://github.com/bacardi55/kalliope-repeat/blame/master/README.md#L72).

**Comment by bacardi55** [comment]
There is no options or return values per say.
basically all options that you set in the brains are available in the return values.
so if you want you can add option called "blabla" and you will have a "blabla" value returned.
Goal is you get what you sent :)

I tried to explain this in the paragraph below the option table and return values table but might not be clear enough.

Thanks for the indentation :)

**Comment by LaMonF** [comment]
## Options

| parameter  | required | default   | choices | comment                                                                                    |
|------------|----------|-----------|---------|--------------------------------------------------------------------------------------------|
|      Query      | Yes|           |     String    |       Your incoming query                                                                                     |


## Return Values

| Name         | Description                                                                           | Type     | sample   |
| ------------ | ------------------------------------------------------------------------------------- | -------- | -------- |
|       Query       |         the query you sent                                                                              |   String       |     This is my query     |

**Comment by bacardi55** [comment]
Thanks, I'll update accordingly. 
Even though I believe this might be confusing as it suggest you can only send 1 arg and not an unlimited number.

**Comment by LaMonF** [comment]
Yes I agree, maybe it is too confusing, but letting it empty is confusing too.

maybe leaving"*" instead of "query"

**Comment by LaMonF** [comment]
## Options

| parameter  | required | default   | choices | comment                                                                                    |
|------------|----------|-----------|---------|--------------------------------------------------------------------------------------------|
|      *      | Yes|           |     String*    |       Your incoming query(ies)                                                                                  |


## Return Values

| Name         | Description                                                                           | Type     | sample   |
| ------------ | ------------------------------------------------------------------------------------- | -------- | -------- |
|       * |         the query(ies) you sent                                                                              |   String*     |     This is my query(ies)    |


What do you think ?

**Comment by bacardi55** [comment]
perfect! i've updated accordingly (:

**Comment by LaMonF** [comment]
PS: seems like the indent is still incorrect :)

**Comment by bacardi55** [comment]
should be good for real this time (:
